## RabbitMQ Configuration
loopback_users.guest = false
listeners.tcp.default = 5672
management.tcp.port = 15672

## Load definitions on startup
load_definitions = /etc/rabbitmq/definitions.json

## Logging
log.console = true
log.console.level = info
